import style from './style';
import * as CSS from 'csstype';

export default ({
  section: null,
  nav: null,
  article: null,
  aside: null,
  h1: {
    ...style.h1_h2_h3_h4_h5_h6,
    ...style.h1,
  },
  h2: {
    ...style.h1_h2_h3_h4_h5_h6,
    ...style.h2,
  },
  h3: {
    ...style.h1_h2_h3_h4_h5_h6,
    ...style.h3,
  },
  h4: {
    ...style.h1_h2_h3_h4_h5_h6,
    ...style.h4,
  },
  h5: {
    ...style.h1_h2_h3_h4_h5_h6,
    ...style.h5,
  },
  h6: {
    ...style.h1_h2_h3_h4_h5_h6,
    ...style.h6,
  },
  header: null,
  footer: null,
  address: null,
  p: style.p,
  hr: style.hr,
  pre: {
    ...style.pre_code_kbd_samp,
    ...style.pre,
  },
  blockquote: null,
  ol: style.ul_ol,
  ul: style.ul_ol,
  li: null,
  dl: null,
  dt: null,
  dd: null,
  figure: null,
  figcaption: null,
  div: null,
  main: style.main,
  a: style.a,
  em: null,
  strong: style.strong,
  small: style.small,
  s: null,
  cite: null,
  q: null,
  dfn: null,
  abbr: style.abbr,
  time: null,
  code: style.pre_code_kbd_samp,
  var: null,
  samp: style.pre_code_kbd_samp,
  kbd: style.pre_code_kbd_samp,
  sub: {
    ...style.sub_sup,
    ...style.sub,
  },
  sup: {
    ...style.sub_sup,
    ...style.sup,
  },
  i: null,
  b: null,
  mark: null,
  ruby: null,
  rt: null,
  rp: null,
  bdo: null,
  span: null,
  wbr: null,
  ins: null,
  del: null,
  img: style.img,
  iframe: null,
  embed: null,
  object: null,
  param: null,
  video: null,
  audio: null,
  source: null,
  canvas: null,
  map: null,
  area: null,
  table: null,
  caption: null,
  colgroup: null,
  col: null,
  tbody: null,
  thead: null,
  tfoot: null,
  tr: null,
  td: null,
  th: null,
  form: null,
  fieldset: style.fieldset,
  legend: style.legend,
  label: null,
  input: {
    ...style.button_input_optgroup_select_textarea,
    ...style.button_input,
  },
  button: {
    ...style.button_input_optgroup_select_textarea,
    ...style.button_input,
    ...style.button_select,
    ...style.button_inputButton_inputReset_inputSubmit,
  },
  select: {
    ...style.button_input_optgroup_select_textarea,
    ...style.button_select,
  },
  datalist: null,
  optgroup: style.button_input_optgroup_select_textarea,
  option: null,
  textarea: {
    ...style.button_input_optgroup_select_textarea,
    ...style.textarea,
  },
  keygen: null,
  output: null,
  progress: style.progress,
  meter: null,
  details: style.details,
  summary: style.summary,
  command: null,
  menu: null,
} as any) as {
  [P in keyof JSX.IntrinsicElements]: CSS.Properties | null;
};
